---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "willkg"
    rebase-strategy: "disabled"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    reviewers:
      - "willkg"
    rebase-strategy: "disabled"
