---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "obs-team"
    rebase-strategy: "disabled"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    reviewers:
      - "obs-team"
    rebase-strategy: "disabled"

  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "obs-team"
    rebase-strategy: "disabled"
