FROM tecken:deploy_base

ENV DJANGO_CONFIGURATION=Dev

EXPOSE $PORT

# Switch to root to install stuff
USER root

# Install build essentials which includes make which we need for docs
# and also vim for easier debugging/editing in the container
RUN apt-get install -y \
    build-essential \
    jed

# Install Python dependencies specifically for building docs
COPY docs-requirements.txt /tmp/
# Switch to /tmp to install dependencies outside home dir
WORKDIR /tmp
RUN pip install --no-cache-dir -r docs-requirements.txt

# Perhaps here we should also pip install stuff that only developers
# need like pytest, coverage, etc.

# Switch back to home directory
WORKDIR /app

# Switch back to 10001 user
USER 10001

CMD ["web-dev"]
