FROM tecken:deploy_base

ENV DJANGO_CONFIGURATION=Dev

EXPOSE $PORT

# Switch to root to install stuff
USER root

# Install build essentials which includes make which we need for docs
# and also vim for easier debugging/editing in the container
RUN apt-get install -y \
    build-essential \
    jed

# Go to /tmp for pip installs
WORKDIR /tmp

# Install Python dependencies specifically for building docs
COPY docs-requirements.txt /tmp/
RUN pip install --no-cache-dir -r docs-requirements.txt

# Install Python dependencies specifically for doing local dev
COPY dev-requirements.txt /tmp/
RUN pip install --no-cache-dir -r dev-requirements.txt

# Switch back to home directory
WORKDIR /app

# Switch back to 10001 user
USER 10001

CMD ["web-dev"]
