[pytest]
norecursedirs = .cache __pycache__
testpaths = tecken/tests/
addopts = -rsxX --showlocals --tb=native --no-migrations -p no:cacheprovider

DJANGO_SETTINGS_MODULE = tecken.settings

# Transform all warnings into errors
filterwarnings =
    error
    # josepy 1.14.0 uses a deprecated api, being addressed in https://github.com/certbot/josepy/pull/182
    ignore:CSR support in pyOpenSSL is deprecated. You should use the APIs in cryptography.:DeprecationWarning:josepy
