# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'permissions': (('manage_tokens', 'Manage Your API Tokens'),)},
        ),
    ]
