# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0003_auto_20171208_1735"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="preferred_upload_api_version",
            field=models.IntegerField(
                choices=[(1, "V1"), (2, "V2")], db_default=1, default=1
            ),
        ),
    ]
