# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_upload_ignored_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'permissions': (('upload_symbols', 'Upload Symbols Files'), ('view_all_uploads', 'View All Symbols Uploads'))},
        ),
    ]
