# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_upload_ignored_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='microsoft_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.Upload'),
        ),
    ]
