# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 1.11.3 on 2017-07-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0004_auto_20170712_1316"),
        ("upload", "0004_auto_20170717_1806"),
    ]

    operations = []
