# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20170712_1316'),
        ('upload', '0004_auto_20170717_1806'),
    ]

    operations = [
    ]
