# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 1.11.3 on 2017-07-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0005_merge_20170718_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
