# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_upload_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
