# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20170831_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='inbox_filepath',
            field=models.FilePathField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='inbox_key',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
