# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 1.11.6 on 2017-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0012_auto_20171009_2038"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="content_hash",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
