# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_auto_20171009_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='content_hash',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
