# -*- coding: utf-8 -*-

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 1.11.6 on 2017-10-24 12:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0013_upload_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="redirect_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=500), null=True, size=None
            ),
        ),
    ]
