# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_upload_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='redirect_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), null=True, size=None),
        ),
    ]
