# -*- coding: utf-8 -*-

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 1.11.7 on 2017-11-30 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_upload_redirect_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'permissions': (('upload_symbols', 'Upload Symbols Files'), ('upload_try_symbols', 'Upload Try Symbols Files'), ('view_all_uploads', 'View All Symbols Uploads'))},
        ),
    ]
