# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20171130_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='try_symbols',
            field=models.BooleanField(default=False),
        ),
    ]
