# Generated by Django 3.2.11 on 2022-01-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0019_auto_20180831_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="uploadscreated",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
