# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 3.2.19 on 2023-06-21 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0020_alter_upload_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadsCreated",
        ),
    ]
