# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 3.2.21 on 2023-09-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0021_delete_uploadscreated"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="code_file",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="code_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="debug_filename",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="debug_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="generator",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
