# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 3.2.21 on 2023-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0022_auto_20230905_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="code_file",
            field=models.TextField(
                blank=True, help_text="The module code file. (sym, Windows)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="code_id",
            field=models.CharField(
                blank=True,
                help_text="The module code id. (sym, Windows)",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="debug_filename",
            field=models.TextField(
                blank=True,
                help_text="The debug filename for the symbol file generated at build time. Examples: libmozsqlite3.so, xul.pdb. (sym)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="debug_id",
            field=models.CharField(
                blank=True,
                help_text="The debug id for the symbol file generated at build time. (sym)",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="generator",
            field=models.CharField(
                blank=True,
                help_text="The tool that generated the sym file. (sym)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                condition=models.Q(
                    ("debug_filename__isnull", False), ("debug_id__isnull", False)
                ),
                fields=["debug_filename", "debug_id"],
                name="upload_fileupload_debuginfo",
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                condition=models.Q(
                    ("code_file__isnull", False), ("code_id__isnull", False)
                ),
                fields=["code_file", "code_id"],
                name="upload_fileupload_codeinfo",
            ),
        ),
    ]
