# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.11 on 2024-06-24 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0023_fileupload_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="bucket_region",
        ),
    ]
