# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("upload", "0025_bug_2049671_fileupload_created_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX CONCURRENTLY "
                        '"upload_fileupload_upload_key_unique" '
                        'ON "upload_fileupload" ("upload_id", "key")'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "upload_fileupload" '
                        'ADD CONSTRAINT "upload_fileupload_upload_key_unique" '
                        "UNIQUE USING INDEX "
                        '"upload_fileupload_upload_key_unique"'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "upload_fileupload" '
                        'DROP CONSTRAINT "upload_fileupload_upload_key_unique"'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="fileupload",
                    constraint=models.UniqueConstraint(
                        fields=("upload", "key"),
                        name="upload_fileupload_upload_key_unique",
                    ),
                ),
            ],
        ),
    ]
