# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0026_fileupload_upload_key_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="outstanding_file_uploads",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
