# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20171016_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingsymbol',
            name='code_file',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='missingsymbol',
            name='code_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
