# Generated by Django 2.2.8 on 2019-12-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0004_auto_20171206_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microsoftdownload",
            name="file_upload",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="upload.FileUpload",
            ),
        ),
    ]
