# Generated by Django 3.2.11 on 2022-01-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0006_delete_microsoftdownload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingsymbol",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
