# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 3.2.20 on 2023-08-11 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("download", "0006_delete_microsoftdownload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MissingSymbol",
        ),
    ]
