FROM mozilla/oidc-testprovider:oidc_testprovider-v0.9.3@sha256:0d275fcbbf27bd901cd739a4ad6753161f78be8fce3b51eb1fe2d75f9f352773

# Modify redirect_urls specified in "fixtures.json" to fit our needs.
COPY fixtures.json /code/fixtures.json
